name = "blog-site"
pages_build_output_dir = "public"
compatibility_date = "2025-04-02"

[vars]
HUGO_BUILD_TAGS = "extended"
HUGO_VERSION = "0.145.0"
PREVIEW = "1"

[env.production.vars]
CF_PAGES_URL = "https://blog.maxmind.com/"
HUGO_BUILD_TAGS = "extended"
HUGO_VERSION = "0.145.0"
