name: Links

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
          fetch-depth: 0
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check links
        run: mise run check-links
